version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=berkay
      - RABBITMQ_DEFAULT_PASS=berkay

#docker-compose -f docker-compose.yml up -d